---
apiVersion: v1
kind: Secret
metadata:
  name: copr-database-secrets
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.database.username | quote }}
  password: {{ .Values.secrets.database.password | quote }}
  database: {{ .Values.secrets.database.database | quote }}
