---
apiVersion: v1
kind: Secret
metadata:
  name: copr-distgit-secrets
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
type: Opaque
stringData:
  frontend-auth: {{ .Values.secrets.distgit.frontendAuth | quote }}
