---
apiVersion: v1
kind: Secret
metadata:
  name: copr-frontend-secrets
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.frontend.secretKey | quote }}
  backend-password: {{ .Values.secrets.frontend.backendPassword | quote }}
