---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-database-data
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.databaseData }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-redis-data
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.redisData }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-results-data
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.resultsData }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-distgit-data
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.distgitData }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-keygen-data
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.keygenData }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-resalloc-data
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.resallocData }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-pulp-storage
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.pulpStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-pulp-database
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.pulpDatabase }}
