"""
add allow_fork_all_builds for copr projects

Revision ID: 7a865da2b61c
Create Date: 2026-09-11 12:39:36.464463
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a865da2b61c'
down_revision = 'e31b4af2468c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr', sa.Column('allow_fork_all_builds', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copr', 'allow_fork_all_builds')
    # ### end Alembic commands ###
