---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copr-backend-config
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
data:
  copr-be.conf: |
{{ .Values.backend.config | indent 4 }}
