---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copr-distgit-config
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
data:
  copr-dist-git.conf: |
{{ .Values.distgit.config | indent 4 }}
