---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copr-frontend-config
  namespace: {{ include "copr.namespace" . }}
  labels:
    {{- include "copr.labels" . | nindent 4 }}
data:
  copr.conf: |
{{ .Values.frontend.config | indent 4 }}
